import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { connectToDatabase } from "@/lib/mongoose";
import  {Toaster} from 'react-hot-toast'
import SocketProvider from "@/context/SocketProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "RentIT - Dashboard",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.png'
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isConn = await connectToDatabase();
  if (isConn !== null) {
    console.log("DB connected");
  } else {
    console.log("DB not connected");
  }
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/icons/logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider/>
        <Toaster/>
        {children}
      </body>
    </html>
  );
}
